[2025-07-13T16:05:59.719+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T16:05:59.740+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.validate_data manual__2025-07-13T16:05:57.643999+00:00 [queued]>
[2025-07-13T16:05:59.750+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.validate_data manual__2025-07-13T16:05:57.643999+00:00 [queued]>
[2025-07-13T16:05:59.751+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T16:05:59.763+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): validate_data> on 2025-07-13 16:05:57.643999+00:00
[2025-07-13T16:05:59.771+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=631) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-13T16:05:59.773+0000] {standard_task_runner.py:72} INFO - Started process 632 to run task
[2025-07-13T16:05:59.773+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'validate_data', 'manual__2025-07-13T16:05:57.643999+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmp9o0xt4cm']
[2025-07-13T16:05:59.774+0000] {standard_task_runner.py:105} INFO - Job 336: Subtask validate_data
[2025-07-13T16:05:59.828+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.validate_data manual__2025-07-13T16:05:57.643999+00:00 [running]> on host a0a54bfbbb9e
[2025-07-13T16:05:59.927+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T16:05:57.643999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T16:05:57.643999+00:00'
[2025-07-13T16:05:59.928+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T16:06:00.438+0000] {logging_mixin.py:190} INFO - Validating file: /opt/airflow/data/raw_data/employee_data_with_errors_chunk_4.csv
[2025-07-13T16:06:00.464+0000] {logging_mixin.py:190} INFO - Validation completed: {'filepath': '/opt/airflow/data/raw_data/employee_data_with_errors_chunk_4.csv', 'total_rows': 91, 'valid_rows': 0, 'invalid_rows': 91, 'criticality': 'high', 'errors_summary': 'Gender: 91 missing values', 'error_counts': {'Employee ID': 0, 'Age': 0, 'Years at Company': 0, 'Job Role': 0, 'Monthly Income': 0, 'Work-Life Balance': 0, 'Job Satisfaction': 0, 'Performance Rating': 0, 'Number of Promotions': 0, 'Overtime': 0, 'Distance from Home': 0, 'Education Level': 0, 'Marital Status': 0, 'Number of Dependents': 0, 'Job Level': 0, 'Company Size': 0, 'Company Tenure': 0, 'Remote Work': 0, 'Leadership Opportunities': 0, 'Innovation Opportunities': 0, 'Company Reputation': 0, 'Employee Recognition': 0, 'Attrition': 0, 'Gender': 91}, 'created_on': '2025-07-13T16:06:00.464039', 'bad_row_indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90], 'validation_status': 'FAILED'}
[2025-07-13T16:06:00.464+0000] {python.py:240} INFO - Done. Returned value was: {'filepath': '/opt/airflow/data/raw_data/employee_data_with_errors_chunk_4.csv', 'total_rows': 91, 'valid_rows': 0, 'invalid_rows': 91, 'criticality': 'high', 'errors_summary': 'Gender: 91 missing values', 'error_counts': {'Employee ID': 0, 'Age': 0, 'Years at Company': 0, 'Job Role': 0, 'Monthly Income': 0, 'Work-Life Balance': 0, 'Job Satisfaction': 0, 'Performance Rating': 0, 'Number of Promotions': 0, 'Overtime': 0, 'Distance from Home': 0, 'Education Level': 0, 'Marital Status': 0, 'Number of Dependents': 0, 'Job Level': 0, 'Company Size': 0, 'Company Tenure': 0, 'Remote Work': 0, 'Leadership Opportunities': 0, 'Innovation Opportunities': 0, 'Company Reputation': 0, 'Employee Recognition': 0, 'Attrition': 0, 'Gender': 91}, 'created_on': '2025-07-13T16:06:00.464039', 'bad_row_indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90], 'validation_status': 'FAILED'}
[2025-07-13T16:06:00.520+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T16:06:00.521+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=employee_ingestion_dag, task_id=validate_data, run_id=manual__2025-07-13T16:05:57.643999+00:00, execution_date=20250713T160557, start_date=20250713T160559, end_date=20250713T160600
[2025-07-13T16:06:00.590+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-13T16:06:00.616+0000] {taskinstance.py:3901} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2025-07-13T16:06:00.618+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
