[2025-07-12T13:53:49.898+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-12T13:53:49.921+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-12T13:53:47.040881+00:00 [queued]>
[2025-07-12T13:53:49.929+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-12T13:53:47.040881+00:00 [queued]>
[2025-07-12T13:53:49.930+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-12T13:53:49.941+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): split_and_save_data> on 2025-07-12 13:53:47.040881+00:00
[2025-07-12T13:53:49.949+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-12T13:53:49.950+0000] {standard_task_runner.py:72} INFO - Started process 1264 to run task
[2025-07-12T13:53:49.950+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'split_and_save_data', 'manual__2025-07-12T13:53:47.040881+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmppwh_yb9p']
[2025-07-12T13:53:49.951+0000] {standard_task_runner.py:105} INFO - Job 270: Subtask split_and_save_data
[2025-07-12T13:53:50.002+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-12T13:53:47.040881+00:00 [running]> on host f80ef267dd5d
[2025-07-12T13:53:50.096+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='split_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T13:53:47.040881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-12T13:53:47.040881+00:00'
[2025-07-12T13:53:50.098+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-12T13:53:50.488+0000] {logging_mixin.py:190} INFO - Processing file: employee_data_with_errors_chunk_2.csv
[2025-07-12T13:53:50.489+0000] {logging_mixin.py:190} INFO - Total rows: 11, Invalid rows: 11
[2025-07-12T13:53:50.493+0000] {logging_mixin.py:190} INFO - File moved to bad_data: /opt/airflow/data/bad_data/employee_data_with_errors_chunk_2.csv
[2025-07-12T13:53:50.495+0000] {logging_mixin.py:190} INFO - Original file removed: /opt/airflow/data/raw_data/employee_data_with_errors_chunk_2.csv
[2025-07-12T13:53:50.495+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-12T13:53:50.508+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-12T13:53:50.508+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=employee_ingestion_dag, task_id=split_and_save_data, run_id=manual__2025-07-12T13:53:47.040881+00:00, execution_date=20250712T135347, start_date=20250712T135349, end_date=20250712T135350
[2025-07-12T13:53:50.606+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-12T13:53:50.625+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-12T13:53:50.627+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
