[2025-07-13T16:01:42.780+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T16:01:42.801+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.send_alerts manual__2025-07-13T16:01:31.229591+00:00 [queued]>
[2025-07-13T16:01:42.810+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.send_alerts manual__2025-07-13T16:01:31.229591+00:00 [queued]>
[2025-07-13T16:01:42.810+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T16:01:42.831+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): send_alerts> on 2025-07-13 16:01:31.229591+00:00
[2025-07-13T16:01:42.841+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=530) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-13T16:01:42.843+0000] {standard_task_runner.py:72} INFO - Started process 534 to run task
[2025-07-13T16:01:42.843+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'send_alerts', 'manual__2025-07-13T16:01:31.229591+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmp9iefj7ue']
[2025-07-13T16:01:42.844+0000] {standard_task_runner.py:105} INFO - Job 307: Subtask send_alerts
[2025-07-13T16:01:42.905+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.send_alerts manual__2025-07-13T16:01:31.229591+00:00 [running]> on host a0a54bfbbb9e
[2025-07-13T16:01:42.991+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='send_alerts' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T16:01:31.229591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T16:01:31.229591+00:00'
[2025-07-13T16:01:42.992+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T16:01:43.006+0000] {ingestion_pipeline.py:219} INFO - HTML report generated: /opt/airflow/great_expectations/uncommitted/data_docs/local_site/validations/validation_report_20250713_160143.html
[2025-07-13T16:01:44.978+0000] {ingestion_pipeline.py:254} INFO - Teams alert sent successfully
[2025-07-13T16:01:44.979+0000] {ingestion_pipeline.py:261} INFO - 
            ðŸš¨ DATA VALIDATION ALERT ðŸš¨
            File: employee_data_with_errors_chunk_3.csv
            Total Rows: 100
            Valid Rows: 0
            Invalid Rows: 100
            Criticality: HIGH
            Issues: Age: 8 missing values; Gender: 100 missing values
            Report: http://localhost:8080/static/validation_reports/validation_report_20250713_160143.html
            
[2025-07-13T16:01:44.980+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-13T16:01:44.993+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T16:01:44.994+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=employee_ingestion_dag, task_id=send_alerts, run_id=manual__2025-07-13T16:01:31.229591+00:00, execution_date=20250713T160131, start_date=20250713T160142, end_date=20250713T160144
[2025-07-13T16:01:45.067+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-13T16:01:45.092+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T16:01:45.095+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
