[2025-07-13T10:38:04.332+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T10:38:04.353+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data scheduled__2025-07-13T10:37:00+00:00 [queued]>
[2025-07-13T10:38:04.364+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data scheduled__2025-07-13T10:37:00+00:00 [queued]>
[2025-07-13T10:38:04.365+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T10:38:04.379+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): split_and_save_data> on 2025-07-13 10:37:00+00:00
[2025-07-13T10:38:04.389+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-13T10:38:04.391+0000] {standard_task_runner.py:72} INFO - Started process 134 to run task
[2025-07-13T10:38:04.392+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'split_and_save_data', 'scheduled__2025-07-13T10:37:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmpxs0ev_fs']
[2025-07-13T10:38:04.393+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask split_and_save_data
[2025-07-13T10:38:04.468+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.split_and_save_data scheduled__2025-07-13T10:37:00+00:00 [running]> on host c45a93548ada
[2025-07-13T10:38:04.565+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='split_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T10:37:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-13T10:37:00+00:00'
[2025-07-13T10:38:04.566+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T10:38:05.122+0000] {logging_mixin.py:190} INFO - Processing file: employee_data2_with_errors_chunk_5.csv
[2025-07-13T10:38:05.123+0000] {logging_mixin.py:190} INFO - Total rows: 2406, Invalid rows: 0
[2025-07-13T10:38:05.146+0000] {logging_mixin.py:190} INFO - File moved to good_data: /opt/airflow/data/good_data/employee_data2_with_errors_chunk_5.csv
[2025-07-13T10:38:05.148+0000] {logging_mixin.py:190} INFO - Original file removed: /opt/airflow/data/raw_data/employee_data2_with_errors_chunk_5.csv
[2025-07-13T10:38:05.148+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-13T10:38:05.159+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T10:38:05.160+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=employee_ingestion_dag, task_id=split_and_save_data, run_id=scheduled__2025-07-13T10:37:00+00:00, execution_date=20250713T103700, start_date=20250713T103804, end_date=20250713T103805
[2025-07-13T10:38:05.250+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-13T10:38:05.265+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T10:38:05.268+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
